### ISSUE TITLE
Remove Themes folder from codebase when using the starterkit

### ISSUE THREAD

**Issue by mgdesign** [sparkfabrik/Locke#5]
Because the Themes folder is not mounted in the container, and because it should not be changed when kickstarting a new project, there is no need to keep it in the local codebase after using the `configure`script.

I suggest to remove it.

**Comment by stickgrinder** [comment]
The initial idea was to leave it there to be mounted for customization. Given we are introducing a `custom.css` strategy instead we can remove it. Yet the theme should be kept in a repository (ideally it can belong to `docker-locke-server` together with `server.js` since those are needed to build the actual image?)
